---
config:
  layout: elk
---
flowchart TD
    OPAccount[fa:fa-user OPAccount]
    OPUser[fa:fa-user OPUser]
    OPGroup[fa:fa-user-group OPGroup]
    OPVault[fa:fa-vault OPVault]
    OPItem[fa:fa-user-secret OPItem]
    OPApiCredential[fa:fa-code OPApiCredential]
    OPCreditCard[fa:fa-credit-card OPCreditCard]
    OPDocument[fa:fa-file OPDocument]
    OPLogin[fa:fa-user-lock OPLogin]
    OPPassport[fa:fa-passport OPPassport]
    OPPassword[fa:fa-key OPPassword]
    OPSecureNote[fa:fa-note-sticky OPSecureNote]
    OPServer[fa:fa-server OPServer]
    OPSoftwareLicense[fa:fa-key OPSoftwareLicense]
    OPSshKey[fa:fa-terminal OPSshKey]
    OPWirelessRouter[fa:fa-wifi OPWirelessRouter]

    style OPAccount fill:#5A8FDC
    style OPUser fill:#F4CA70
    style OPGroup fill:#FF8369
    style OPVault fill:#6AE4A9
    style OPItem fill:#C04EA0
    style OPApiCredential fill:#FFF6EB
    style OPCreditCard fill:#FFF6EB
    style OPDocument fill:#FFF6EB
    style OPLogin fill:#FFF6EB
    style OPPassport fill:#FFF6EB
    style OPPassword fill:#FFF6EB
    style OPSecureNote fill:#FFF6EB
    style OPServer fill:#FFF6EB
    style OPSoftwareLicense fill:#FFF6EB
    style OPSshKey fill:#FFF6EB
    style OPWirelessRouter fill:#FFF6EB
    
    OPAccount -.->|OPContains| OPItem
    OPAccount -.->|OPContains| OPUser
    OPAccount -.->|OPContains| OPVault
    OPAccount -.->|OPContains| OPGroup

    OPUser -->|OPMemberOf| OPGroup
    OPUser -.->|OPManagerOf| OPGroup

    OPUser -->|OPViewItems| OPVault
%%  OPUser -.->|OPCreateItems| OPVault
%%  OPUser -.->|OPEditItems| OPVault
%%  OPUser -.->|OPArchiveItems| OPVault
%%  OPUser -.->|OPDeleteItems| OPVault
    OPUser -->|OPManageVault| OPVault
%% These represent "Client Settings" that are only applied at the application layer %%
%%  OPUser -.->|OPViewAndCopyPasswords| OPVault
%%  OPUser -.->|OPViewItemHistory| OPVault
%%  OPUser -.->|OPImportItems| OPVault
%%  OPUser -.->|OPExportItems| OPVault
%%  OPUser -.->|OPCopyAndShareItems| OPVault
%%  OPUser -.->|OPPrintItems| OPVault

    OPGroup -->|OPAddMember| OPGroup

    OPGroup -->|OPViewItems| OPVault
%%  OPUser -.->|OPCreateItems| OPVault
%%  OPUser -.->|OPEditItems| OPVault
%%  OPUser -.->|OPArchiveItems| OPVault
%%  OPUser -.->|OPDeleteItems| OPVault
    OPGroup -->|OPManageVault| OPVault
%% These represent "Client Settings" that are only applied at the application layer %%
%%  OPUser -.->|OPViewAndCopyPasswords| OPVault
%%  OPUser -.->|OPViewItemHistory| OPVault
%%  OPUser -.->|OPImportItems| OPVault
%%  OPUser -.->|OPExportItems| OPVault
%%  OPUser -.->|OPCopyAndShareItems| OPVault
%%  OPUser -.->|OPPrintItems| OPVault

%%  OPGroup -.->|OPAddPerson| OPAccount
%%  OPGroup -.->|OPChangePersonName| OPAccount
%%  OPGroup -.->|OPChangeTeamAttributes| OPAccount
%%  OPGroup -.->|OPChangeTeamDomain| OPAccount
%%  OPGroup -.->|OPChangeTeamSettings| OPAccount
%%  OPGroup -.->|OPCreateVaults| OPAccount
%%  OPGroup -.->|OPDeletePerson| OPAccount
%%  OPGroup -.->|OPDeleteTeam| OPAccount
%%  OPGroup -.->|OPManageBilling| OPAccount
%% OPManageGroups is used to generate the OPCanAddMember edge %%
    OPGroup -.->|OPManageGroups| OPAccount
%%  OPGroup -.->|OPManageTemplates| OPAccount
%% OPManageVaults seemed promising, but it essentially guarantees OPManageVault over all newly created Vaults which is already represented %%
%%  OPGroup -.->|OPManageVaults| OPAccount
%%  OPGroup -.->|OPProvisionPeople| OPAccount
%% I have not completely validated the recovery workflow, but this seems to be an account takeover primitive %%
    OPGroup -.->|OPRecoverAccounts| OPAccount
%%  OPGroup -.->|OPSuspendPerson| OPAccount
%%  OPGroup -.->|OPSuspendTeam| OPAccount
%%  OPGroup -.->|OPViewActivitiesLog| OPAccount
%%  OPGroup -.->|OPViewAdministrativeSidebar| OPAccount
%%  OPGroup -.->|OPViewBilling| OPAccount
%%  OPGroup -.->|OPViewPeople| OPAccount
%%  OPGroup -.->|OPViewTeamSettings| OPAccount
%%  OPGroup -.->|OPViewTemplates| OPAccount
%%  OPGroup -.->|OPViewVaults| OPAccount

    OPVault -->|OPHasItem| OPItem
    OPVault -->|OPHasItem| OPApiCredential
    OPVault -->|OPHasItem| OPCreditCard
    OPVault -->|OPHasItem| OPDocument
    OPVault -->|OPHasItem| OPLogin
    OPVault -->|OPHasItem| OPPassport
    OPVault -->|OPHasItem| OPPassword
    OPVault -->|OPHasItem| OPSecureNote
    OPVault -->|OPHasItem| OPServer
    OPVault -->|OPHasItem| OPSoftwareLicense
    OPVault -->|OPHasItem| OPSshKey
    OPVault -->|OPHasItem| OPWirelessRouter
